export const ALL_PERMISSIONS = {
  dashboard: { label: "Dashboard", group: "Genel" },

  products_view: { label: "Ürünleri Görüntüle", group: "Ürün Yönetimi" },
  products_create: { label: "Ürün Ekle", group: "Ürün Yönetimi" },
  products_edit: { label: "Ürün Düzenle", group: "Ürün Yönetimi" },
  products_delete: { label: "Ürün Sil", group: "Ürün Yönetimi" },
  products_bulk: { label: "Toplu Ürün İşlemleri", group: "Ürün Yönetimi" },

  categories_view: { label: "Kategorileri Görüntüle", group: "Ürün Yönetimi" },
  categories_manage: { label: "Kategori Yönet", group: "Ürün Yönetimi" },

  dealers_view: { label: "Bayileri Görüntüle", group: "Bayi Yönetimi" },
  members_view: { label: "Üyeleri Görüntüle", group: "Bayi Yönetimi" },
  members_manage: { label: "Üye Onayla / Reddet", group: "Bayi Yönetimi" },
  dealers_create: { label: "Bayi Ekle", group: "Bayi Yönetimi" },
  dealers_edit: { label: "Bayi Düzenle", group: "Bayi Yönetimi" },
  dealers_delete: { label: "Bayi Sil", group: "Bayi Yönetimi" },
  dealer_groups_manage: { label: "Bayi Gruplarını Yönet", group: "Bayi Yönetimi" },
  dealer_prices_manage: { label: "Özel Fiyatları Yönet", group: "Bayi Yönetimi" },
  catalog_restrictions: { label: "Katalog Kısıtlamaları", group: "Bayi Yönetimi" },

  orders_view: { label: "Siparişleri Görüntüle", group: "Sipariş & Finans" },
  orders_approve: { label: "Sipariş Onayla", group: "Sipariş & Finans" },
  orders_cancel: { label: "Sipariş İptal Et", group: "Sipariş & Finans" },
  orders_ship: { label: "Sipariş Sevk Et", group: "Sipariş & Finans" },
  orders_backorder: { label: "Ön Sipariş Yönetimi", group: "Sipariş & Finans" },

  payments_view: { label: "Ödemeleri Görüntüle", group: "Sipariş & Finans" },
  payments_manage: { label: "Ödeme Yönet", group: "Sipariş & Finans" },

  returns_view: { label: "İadeleri Görüntüle", group: "Sipariş & Finans" },
  returns_manage: { label: "İade Yönet", group: "Sipariş & Finans" },

  campaigns_manage: { label: "Kampanya Yönet", group: "Sipariş & Finans" },
  coupons_manage: { label: "Kupon Yönet", group: "Sipariş & Finans" },
  quotes_manage: { label: "Teklif Yönet", group: "Sipariş & Finans" },

  stock_view: { label: "Stok Görüntüle", group: "Stok & Depo" },
  stock_manage: { label: "Stok Yönet (Giriş/Çıkış/Sayım)", group: "Stok & Depo" },
  stock_transfer: { label: "Depolar Arası Transfer", group: "Stok & Depo" },
  warehouses_manage: { label: "Depo Yönet", group: "Stok & Depo" },
  shipping_manage: { label: "Kargo Yönetimi", group: "Stok & Depo" },

  admin_users: { label: "Admin Kullanıcılarını Yönet", group: "Kullanıcılar" },
  admin_roles: { label: "Rolleri Yönet", group: "Kullanıcılar" },
  admin_notifications: { label: "Bildirimleri Görüntüle", group: "Kullanıcılar" },
  admin_logs_view: { label: "Admin Loglarını Görüntüle", group: "Kullanıcılar" },

  dealer_transactions_view: { label: "Bakiye Hareketlerini Görüntüle", group: "Sipariş & Finans" },

  marketplace_view: { label: "Pazar Yeri Entegrasyonu", group: "Genel" },
  invoices_view: { label: "Faturaları Görüntüle", group: "Sipariş & Finans" },
  thyronix_view: { label: "Thyronix Yönetimini Görüntüle", group: "Premium Ürünler" },
  hive_view: { label: "HIVE Yönetimini Görüntüle", group: "Premium Ürünler" },
  hive_manage: { label: "HIVE Yönet", group: "Premium Ürünler" },
  hive_integrations: { label: "HIVE Entegrasyonları", group: "Premium Ürünler" },
  hive_logs: { label: "HIVE Logları", group: "Premium Ürünler" },

  reports_view: { label: "Raporları Görüntüle", group: "Raporlar" },
  reports_export: { label: "Rapor Dışa Aktar", group: "Raporlar" },

  settings_view: { label: "Ayarları Görüntüle", group: "Ayarlar" },
  settings_manage: { label: "Ayarları Yönet", group: "Ayarlar" },
  pages_manage: { label: "Site Sayfalarını Yönet", group: "Site & İçerik" },
  ecosystem_view: { label: "Ecosystem Showcase Görüntüle", group: "Ecosystem" },
  ecosystem_manage: { label: "Ecosystem Showcase Yönet", group: "Ecosystem" },

  partners_view: { label: "Partner Ecosystem Görüntüle", group: "Partner Ecosystem" },
  partners_manage: { label: "Partner Ecosystem Yönet", group: "Partner Ecosystem" },
  pod_view: { label: "POD Merkezi Görüntüle", group: "Partner Ecosystem" },

  blog_view: { label: "Blog Merkezi Görüntüle", group: "İçerik Yönetimi" },
  blog_manage: { label: "Blog Merkezi Yönet", group: "İçerik Yönetimi" },
  content_quality_view: { label: "İçerik Kalite Merkezi", group: "İçerik Yönetimi" },
  content_planning_view: { label: "İçerik Planlama Merkezi", group: "İçerik Yönetimi" },
  publishing_view: { label: "Yayın Merkezi", group: "İçerik Yönetimi" },
  legacy_recovery_view: { label: "Link Kurtarma Merkezi", group: "İçerik Yönetimi" },
  geo_factory_view: { label: "GEO İçerik Fabrikası", group: "İçerik Yönetimi" },
} as const;

export type PermissionKey = keyof typeof ALL_PERMISSIONS;

export function hasPermission(permissions: string[] | undefined, permission: PermissionKey): boolean {
  if (!permissions || permissions.length === 0) return false;
  if (permissions.includes("*")) return true;
  return permissions.includes(permission);
}

export function hasAnyPermission(permissions: string[] | undefined, ...perms: PermissionKey[]): boolean {
  if (!permissions) return false;
  if (permissions.includes("*")) return true;
  return perms.some((p) => permissions.includes(p));
}

export const DEFAULT_ADMIN_PERMISSIONS: PermissionKey[] = [
  "dashboard",
  "products_view", "products_create", "products_edit", "products_delete", "products_bulk",
  "categories_view", "categories_manage",
  "dealers_view", "dealers_create", "dealers_edit", "dealers_delete",
  "members_view", "members_manage",
  "dealer_groups_manage", "dealer_prices_manage", "catalog_restrictions",
  "orders_view", "orders_approve", "orders_cancel", "orders_ship", "orders_backorder",
  "payments_view", "payments_manage",
  "returns_view", "returns_manage",
  "campaigns_manage", "coupons_manage", "quotes_manage",
  "stock_view", "stock_manage", "stock_transfer", "warehouses_manage", "shipping_manage",
  "admin_users", "admin_roles", "admin_notifications", "admin_logs_view",
  "dealer_transactions_view",
  "marketplace_view", "invoices_view", "thyronix_view", "hive_view", "hive_manage", "hive_integrations", "hive_logs",
  "reports_view", "reports_export",
  "settings_view", "settings_manage", "pages_manage",
  "ecosystem_view", "ecosystem_manage",
  "partners_view", "partners_manage", "pod_view",
  "blog_view", "blog_manage",
  "content_quality_view", "content_planning_view",
  "publishing_view", "legacy_recovery_view", "geo_factory_view",
];

export function getNavPermissionMap(): Record<string, PermissionKey[]> {
  return {
    "/admin": ["dashboard"],
    "/admin/products": ["products_view"],
    "/admin/categories": ["categories_view"],
    "/admin/price-lists": ["dealers_view"],
    "/admin/tiered-prices": ["dealers_view"],
    "/admin/dealer-prices": ["dealer_prices_manage"],
    "/admin/catalog-restrictions": ["catalog_restrictions"],
    "/admin/reviews": ["products_view"],
    "/admin/bundles": ["products_create"],
    "/admin/contracts": ["settings_view"],
    "/admin/legal-audit": ["settings_view"],
    "/admin/pages": ["pages_manage", "settings_manage"],
    "/admin/site-settings": ["settings_manage"],
    "/admin/footer-settings": ["settings_manage"],
    "/admin/homepage": ["settings_manage"],
    "/admin/dealers": ["dealers_view"],
    "/admin/members": ["members_view", "members_manage", "dealers_view"],
    "/admin/dealer-approvals": ["members_view", "dealers_view"],
    "/admin/dealer-groups": ["dealer_groups_manage"],
    "/admin/partner-applications": ["dealers_view"],
    "/admin/api-keys": ["dealers_view"],
    "/admin/orders": ["orders_view"],
    "/admin/backorders": ["orders_backorder"],
    "/admin/quotes": ["quotes_manage"],
    "/admin/coupons": ["coupons_manage"],
    "/admin/campaigns": ["campaigns_manage"],
    "/admin/returns": ["returns_view"],
    "/admin/payments": ["payments_view"],
    "/admin/payments/policies": ["payments_manage"],
    "/admin/payment-terms": ["payments_view"],
    "/admin/stock-movements": ["stock_view"],
    "/admin/stock-counts": ["stock_manage"],
    "/admin/stock/scan": ["stock_view"],
    "/admin/warehouses": ["warehouses_manage"],
    "/admin/shipping": ["shipping_manage"],
    "/admin/users": ["admin_users"],
    "/admin/roles": ["admin_roles"],
    "/admin/notifications": ["admin_notifications"],
    "/admin/reports": ["reports_view"],
    "/admin/approval-rules": ["settings_manage"],
    "/admin/webhooks": ["settings_manage"],
    "/admin/dealer-documents": ["dealers_view"],
    "/admin/dealer-assignments": ["dealers_view"],
    "/admin/sales-rep": ["dealers_view"],
    "/admin/admin-logs": ["admin_logs_view"],
    "/admin/dealer-transactions": ["dealer_transactions_view"],
    "/admin/marketplace": ["marketplace_view"],
    "/admin/invoices": ["invoices_view"],
    "/admin/thyronix": ["thyronix_view"],
    "/admin/nexa": ["thyronix_view"],
    "/admin/hive": ["hive_view"],
    "/admin/integrations/thyronix": ["thyronix_view", "hive_integrations"],
    "/admin/integrations/hive": ["hive_view", "hive_integrations"],
    "/admin/module-licenses": ["admin_users"],
    "/admin/payments/module-payments": ["payments_view"],
    "/admin/payments/gateways": ["payments_view"],
    "/admin/customer-products": ["admin_users"],
    "/admin/product-links": ["admin_users"],
    "/admin/product-library": ["products_view"],
    "/admin/marketplace-hub": ["marketplace_view"],
    "/admin/ecosystem": ["ecosystem_view"],
    "/admin/partners": ["partners_view", "partners_manage"],
    "/admin/partners/applications": ["partners_view", "partners_manage"],
    "/admin/partners/network": ["partners_view", "partners_manage"],
    "/admin/partners/affiliates": ["partners_view", "partners_manage"],
    "/admin/partners/commissions": ["partners_view", "partners_manage"],
    "/admin/partners/payouts": ["partners_view", "partners_manage"],
    "/admin/partners/[id]": ["partners_view", "partners_manage"],
    "/admin/pod": ["pod_view", "partners_manage"],
    "/admin/pod-tasarim-studyo": ["pod_view", "partners_manage"],
    "/admin/pod/templates": ["pod_view", "partners_manage"],
    "/admin/pod/designs": ["pod_view", "partners_manage"],
    "/admin/pod/orders": ["pod_view", "partners_manage"],
    "/admin/pod/production": ["pod_view", "partners_manage"],
    "/admin/page-factory": ["partners_view", "partners_manage"],
    "/admin/page-factory/data": ["partners_view", "partners_manage"],
    "/admin/page-factory/data/import": ["partners_view", "partners_manage"],
    "/admin/linkslash": ["partners_view", "partners_manage"],
    "/admin/linkslash/android": ["partners_view", "partners_manage"],
    "/admin/dropship": ["partners_view", "partners_manage"],
  "/admin/blog-engine": ["blog_view", "blog_manage"],
  "/admin/geo-icerik-fabrikasi": ["geo_factory_view", "settings_view"],
  "/admin/icerik-planlama-merkezi": ["content_planning_view", "settings_view"],
  "/admin/icerik-kalite-merkezi": ["content_quality_view", "settings_view"],
  "/admin/link-kurtarma-merkezi": ["legacy_recovery_view", "settings_view"],
  "/admin/yayin-merkezi": ["publishing_view", "settings_view"],
  "/admin/icerik-operasyon-merkezi": ["content_planning_view", "publishing_view", "settings_view"],
  "/admin/product-universe": ["partners_view", "partners_manage"],
  "/admin/module-plans": ["admin_users"],
  };
}
