import type { PodProductProfile } from "./pod-product-profile-types";

/**
 * POD profile seed data — canonical runtime reads go through Product Engine graph
 * (@/lib/product-engine/product-graph). Do not duplicate product definitions elsewhere.
 */
export const POD_PRODUCT_PROFILES: PodProductProfile[] = [
  {
    id: "CAM_TABLO",
    name: "Cam Tablo",
    category: "Cam Tablo",
    templateType: "glass-rectangle",
    templateId: "cam-tablo-front",
    catalogId: "CAM",
    pricingRuleCode: "CAM_CATALOG_V1",
    defaultSize: { widthCm: 90, heightCm: 60 },
    shape: "RECTANGLE",
    allowedOrientations: ["landscape", "portrait"],
    printAreaMode: "RECTANGLE",
    mockupType: "GLASS_RECTANGLE",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "GLASS_M2",
    variantId: "cam-tablo-front-v1",
    defaultQuantity: 1,
    options: ["postKesim"],
    status: "active",
  },
  {
    id: "CAM_YUVARLAK",
    name: "Yuvarlak Cam",
    category: "Yuvarlak Cam",
    templateType: "glass-circle",
    templateId: "cam-yuvarlak-front",
    catalogId: "CAM",
    pricingRuleCode: "CAM_CATALOG_V1",
    defaultSize: { widthCm: 60, heightCm: 60 },
    defaultSizeVariantKey: "round",
    shape: "CIRCLE",
    allowedOrientations: ["landscape", "portrait"],
    printAreaMode: "CIRCLE",
    mockupType: "GLASS_CIRCLE",
    editorPlugin: "standard",
    exportMode: "CIRCULAR_CLIP",
    formulaHint: "AREA",
    materialCode: "GLASS_M2",
    variantId: "cam-yuvarlak-v1",
    defaultQuantity: 1,
    options: ["postKesim"],
    status: "active",
  },
  {
    id: "MDF_TABLO",
    name: "MDF Tablo",
    category: "MDF Tablo",
    templateType: "mdf-rectangle",
    templateId: "mdf-tablo-front",
    catalogId: "MDF_TABLO",
    pricingRuleCode: "MDF_TABLO_CATALOG_V1",
    defaultSize: { widthCm: 50, heightCm: 70 },
    shape: "RECTANGLE",
    allowedOrientations: ["landscape", "portrait"],
    printAreaMode: "RECTANGLE",
    mockupType: "MDF_RECTANGLE",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "MDF_M2",
    variantId: "mdf-tablo-v1",
    defaultQuantity: 1,
    status: "active",
  },
  {
    id: "MDF_PUZZLE",
    name: "MDF Puzzle",
    category: "MDF Puzzle",
    templateType: "puzzle-grid",
    templateId: "mdf-puzzle-front",
    catalogId: "MDF_PUZZLE",
    pricingRuleCode: "MDF_PUZZLE_CATALOG_V1",
    defaultSize: { widthCm: 30, heightCm: 30 },
    shape: "PUZZLE",
    allowedOrientations: ["portrait", "landscape"],
    printAreaMode: "RECTANGLE",
    mockupType: "PUZZLE_GRID",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "MDF_M2",
    variantId: "mdf-puzzle-v1",
    defaultQuantity: 1,
    status: "active",
  },
  {
    id: "HALI",
    name: "Halı",
    category: "Halı",
    templateType: "carpet-room",
    templateId: "hali-front",
    catalogId: "HALI",
    pricingRuleCode: "CARPET_CATALOG_V1",
    defaultSize: { widthCm: 200, heightCm: 300 },
    shape: "RECTANGLE",
    allowedOrientations: ["landscape", "portrait"],
    printAreaMode: "RECTANGLE",
    mockupType: "CARPET_ROOM",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "CARPET_M2",
    variantId: "hali-v1",
    defaultQuantity: 1,
    options: ["postKesim", "overlok"],
    status: "active",
  },
  {
    id: "KILIM",
    name: "Kilim",
    category: "Kilim",
    templateType: "rug-room",
    templateId: "kilim-front",
    catalogId: "HALI",
    pricingRuleCode: "CARPET_CATALOG_V1",
    defaultSize: { widthCm: 150, heightCm: 200 },
    shape: "RECTANGLE",
    allowedOrientations: ["landscape", "portrait"],
    printAreaMode: "RECTANGLE",
    mockupType: "RUG_ROOM",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "CARPET_M2",
    variantId: "kilim-v1",
    defaultQuantity: 1,
    options: ["postKesim"],
    status: "active",
  },
  {
    id: "PERDE",
    name: "Perde",
    category: "Perde",
    templateType: "curtain-window",
    templateId: "perde-front",
    catalogId: "PERDE",
    pricingRuleCode: "CURTAIN_CATALOG_V1",
    defaultSize: { widthCm: 280, heightCm: 240 },
    shape: "RECTANGLE",
    allowedOrientations: ["portrait"],
    printAreaMode: "FABRIC_PANEL",
    mockupType: "CURTAIN_WINDOW",
    editorPlugin: "fabric-panel",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "CURTAIN_METER",
    variantId: "perde-v1",
    defaultQuantity: 1,
    status: "active",
  },
  {
    id: "KIRLENT",
    name: "Kırlent",
    category: "Kırlent",
    templateType: "pillow",
    templateId: "kirlent-front",
    catalogId: "KIRLENT",
    pricingRuleCode: "CUSHION_CATALOG_V1",
    defaultSize: { widthCm: 50, heightCm: 50 },
    shape: "SQUARE",
    allowedOrientations: ["portrait", "landscape"],
    printAreaMode: "RECTANGLE",
    mockupType: "PILLOW",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "PIECE",
    materialCode: "CUSHION_PIECE",
    variantId: "kirlent-v1",
    defaultQuantity: 1,
    options: ["single", "pack4"],
    status: "active",
  },
  {
    id: "NEVRESIM",
    name: "Nevresim Takımı",
    category: "Nevresim",
    templateType: "bedding-set",
    templateId: "nevresim-set",
    catalogId: "NEVRESIM",
    pricingRuleCode: "BEDDING_CATALOG_V1",
    defaultSize: { widthCm: 160, heightCm: 220 },
    defaultSizeVariantKey: "single",
    shape: "MULTI_PART",
    allowedOrientations: ["landscape"],
    printAreaMode: "RECTANGLE",
    mockupType: "BEDDING_SET",
    editorPlugin: "multi-part",
    exportMode: "MULTI_PART",
    formulaHint: "PIECE",
    materialCode: "BEDDING_SET",
    variantId: "single",
    defaultQuantity: 1,
    warnings: ["Çok parçalı ürün — parça bazlı düzenleme V2'de detaylanacak."],
    status: "active",
  },
  {
    id: "POSTER",
    name: "Poster",
    category: "Poster",
    templateType: "poster-frame",
    templateId: "poster-portrait",
    catalogId: "POSTER",
    pricingRuleCode: "POSTER_M2_V1",
    defaultSize: { widthCm: 70, heightCm: 100 },
    shape: "RECTANGLE",
    allowedOrientations: ["portrait", "landscape"],
    printAreaMode: "RECTANGLE",
    mockupType: "POSTER_FRAME",
    editorPlugin: "standard",
    exportMode: "PRINT_AREA",
    formulaHint: "AREA",
    materialCode: "POSTER_M2",
    variantId: "poster-portrait-v1",
    defaultQuantity: 1,
    status: "beta",
  },
  {
    id: "KUPA",
    name: "Kupa",
    category: "Kupa",
    templateType: "mug-wrap",
    templateId: "mug-front",
    catalogId: "MUG",
    pricingRuleCode: "MUG_PIECE_V1",
    defaultSize: { widthCm: 0, heightCm: 0 },
    shape: "WRAP",
    allowedOrientations: ["landscape"],
    printAreaMode: "RECTANGLE",
    mockupType: "MUG_WRAP",
    editorPlugin: "wrap",
    exportMode: "WRAP",
    formulaHint: "PIECE",
    materialCode: "MUG_PIECE",
    variantId: "mug-front-v1",
    defaultQuantity: 1,
    status: "beta",
  },
];

export function listPodProductProfiles(): PodProductProfile[] {
  return [...POD_PRODUCT_PROFILES];
}

export function getPodProductProfile(id: string): PodProductProfile | undefined {
  return POD_PRODUCT_PROFILES.find((p) => p.id === id);
}

export function getPodProductProfileByTemplateId(templateId: string): PodProductProfile | undefined {
  return POD_PRODUCT_PROFILES.find((p) => p.templateId === templateId);
}

export function listPodProductCategories(): string[] {
  return [...new Set(POD_PRODUCT_PROFILES.map((p) => p.category))];
}
