import type { StoreTheme } from "./types";

export const STORE_THEMES: StoreTheme[] = [
  {
    name: "minimal-light",
    label: "Minimal Light",
    description: "Beyaz zemin, sade header, ince çerçeveli kartlar",
    previewColor: "#f8fafc",
    colors: {
      primaryColor: "#2563eb",
      secondaryColor: "#7c3aed",
      backgroundColor: "#ffffff",
      textColor: "#1e293b",
      headerBg: "#ffffff",
      footerBg: "#f1f5f9",
      cardBg: "#ffffff",
      buttonStyle: "rounded",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "bordered",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
      { label: "İletişim", href: "/contact", order: 3 },
    ],
    footerGroups: [
      { title: "Kategoriler", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Yardım", links: [{ label: "İletişim", href: "/contact" }, { label: "SSS", href: "/faq" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Hoş Geldiniz", subtitle: "En iyi ürünler burada", ctaText: "Alışverişe Başla", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "dark-elegance",
    label: "Dark Elegance",
    description: "Koyu zemin, altın aksan, lüks his",
    previewColor: "#0a0a0a",
    colors: {
      primaryColor: "#d4a52d",
      secondaryColor: "#8b6914",
      backgroundColor: "#0a0a0a",
      textColor: "#f5f5f5",
      headerBg: "#111111",
      footerBg: "#0d0d0d",
      cardBg: "#1a1a1a",
      buttonStyle: "pill",
    },
    fonts: { headingFont: "Playfair Display", bodyFont: "Inter" },
    layout: {
      headerStyle: "center",
      footerStyle: "default",
      cardStyle: "elevated",
      bannerHeight: "large",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Koleksiyon", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Koleksiyon", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Kurumsal", links: [{ label: "Hakkımızda", href: "/about" }, { label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Zarafet Koleksiyonu", subtitle: "Özel tasarım ürünler", ctaText: "Keşfet", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "nature-green",
    label: "Nature Green",
    description: "Yeşil tonları, doğal görseller, sakin tasarım",
    previewColor: "#f0fdf4",
    colors: {
      primaryColor: "#16a34a",
      secondaryColor: "#15803d",
      backgroundColor: "#f0fdf4",
      textColor: "#14532d",
      headerBg: "#ffffff",
      footerBg: "#dcfce7",
      cardBg: "#ffffff",
      buttonStyle: "rounded",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "bordered",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Ürünler", links: [{ label: "Tümü", href: "/products" }] },
      { title: "Destek", links: [{ label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Doğadan Size", subtitle: "Doğal ve kaliteli ürünler", ctaText: "İncele", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "ocean-blue",
    label: "Ocean Blue",
    description: "Mavi tonları, yumuşak geçişler, ferah tasarım",
    previewColor: "#eff6ff",
    colors: {
      primaryColor: "#0ea5e9",
      secondaryColor: "#0284c7",
      backgroundColor: "#eff6ff",
      textColor: "#0c4a6e",
      headerBg: "#ffffff",
      footerBg: "#e0f2fe",
      cardBg: "#ffffff",
      buttonStyle: "rounded",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "bordered",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Kategoriler", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Yardım", links: [{ label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Mavinin Tonları", subtitle: "Kaliteli ürünler uygun fiyatlarla", ctaText: "Alışverişe Başla", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "midnight-neon",
    label: "Midnight Neon",
    description: "Mor/siyah arka plan, parlak vurgular, modern",
    previewColor: "#09090b",
    colors: {
      primaryColor: "#a855f7",
      secondaryColor: "#ec4899",
      backgroundColor: "#09090b",
      textColor: "#fafafa",
      headerBg: "#111113",
      footerBg: "#0a0a0b",
      cardBg: "#18181b",
      buttonStyle: "pill",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "minimal",
      cardStyle: "elevated",
      bannerHeight: "large",
      bannerOverlay: false,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Koleksiyon", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Linkler", links: [{ label: "Ürünler", href: "/products" }, { label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Neon Koleksiyonu", subtitle: "Geceye özel tasarımlar", ctaText: "Görüntüle", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "vintage-bazaar",
    label: "Vintage Bazaar",
    description: "Sıcak tonlar, nostaljik fontlar, samimi atmosfer",
    previewColor: "#fef3c7",
    colors: {
      primaryColor: "#d97706",
      secondaryColor: "#92400e",
      backgroundColor: "#fef3c7",
      textColor: "#451a03",
      headerBg: "#fffbeb",
      footerBg: "#fde68a",
      cardBg: "#fffbeb",
      buttonStyle: "rounded",
    },
    fonts: { headingFont: "Playfair Display", bodyFont: "Inter" },
    layout: {
      headerStyle: "center",
      footerStyle: "default",
      cardStyle: "bordered",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Mağaza", href: "/products", order: 2 },
      { label: "Hakkımızda", href: "/about", order: 3 },
    ],
    footerGroups: [
      { title: "Alışveriş", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Bilgi", links: [{ label: "Hakkımızda", href: "/about" }, { label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Vintage Koleksiyonu", subtitle: "Geçmişin izleri bugün", ctaText: "Gezintiye Başla", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "corporate-clean",
    label: "Corporate Clean",
    description: "Profesyonel, kurumsal görünüm, sade ve güvenilir",
    previewColor: "#f8fafc",
    colors: {
      primaryColor: "#1e40af",
      secondaryColor: "#3b82f6",
      backgroundColor: "#f8fafc",
      textColor: "#1e293b",
      headerBg: "#ffffff",
      footerBg: "#1e293b",
      cardBg: "#ffffff",
      buttonStyle: "sharp",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "flat",
      bannerHeight: "small",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
      { label: "Kurumsal", href: "/about", order: 3 },
    ],
    footerGroups: [
      { title: "Hızlı Erişim", links: [{ label: "Ana Sayfa", href: "/" }, { label: "Tüm Ürünler", href: "/products" }] },
      { title: "Kurumsal", links: [{ label: "Hakkımızda", href: "/about" }, { label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Profesyonel Çözümler", subtitle: "Kurumsal kalitede ürünler", ctaText: "İncele", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "modern-minimal",
    label: "Modern Minimal",
    description: "Bol boşluk, ince tipografi, sade şıklık",
    previewColor: "#fafafa",
    colors: {
      primaryColor: "#18181b",
      secondaryColor: "#52525b",
      backgroundColor: "#fafafa",
      textColor: "#18181b",
      headerBg: "#ffffff",
      footerBg: "#f4f4f5",
      cardBg: "#ffffff",
      buttonStyle: "sharp",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "minimal",
      footerStyle: "minimal",
      cardStyle: "flat",
      bannerHeight: "large",
      bannerOverlay: false,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Koleksiyon", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Keşfet", links: [{ label: "Koleksiyon", href: "/products" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Az Çoktur", subtitle: "Seçkin ürünler, sade sunum", ctaText: "Keşfet", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "bold-orange",
    label: "Bold Orange",
    description: "Turuncu ağırlıklı, enerjik, dikkat çekici",
    previewColor: "#fff7ed",
    colors: {
      primaryColor: "#ea580c",
      secondaryColor: "#c2410c",
      backgroundColor: "#fff7ed",
      textColor: "#1c1917",
      headerBg: "#ffffff",
      footerBg: "#ffedd5",
      cardBg: "#ffffff",
      buttonStyle: "rounded",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "elevated",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Kategoriler", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Yardım", links: [{ label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Fırsatlar", subtitle: "Kaçırılmayacak ürünler", ctaText: "Hemen İncele", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "luxury-gold",
    label: "Luxury Gold",
    description: "Siyah + altın kombinasyonu, premium his",
    previewColor: "#050505",
    colors: {
      primaryColor: "#f59e0b",
      secondaryColor: "#b45309",
      backgroundColor: "#050505",
      textColor: "#fef3c7",
      headerBg: "#0a0a0a",
      footerBg: "#080808",
      cardBg: "#111111",
      buttonStyle: "pill",
    },
    fonts: { headingFont: "Playfair Display", bodyFont: "Inter" },
    layout: {
      headerStyle: "center",
      footerStyle: "default",
      cardStyle: "elevated",
      bannerHeight: "large",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Lüks", href: "/products", order: 1 },
      { label: "Koleksiyon", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Koleksiyonlar", links: [{ label: "Yeni Sezon", href: "/products" }, { label: "Özel Tasarım", href: "/products" }] },
      { title: "Müşteri Hizmetleri", links: [{ label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Premium Koleksiyon", subtitle: "Altın dokunuşlu özel parçalar", ctaText: "Satın Al", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "pastel-soft",
    label: "Pastel Soft",
    description: "Pastel tonlar, yumuşak geçişler, tatlı tasarım",
    previewColor: "#fdf2f8",
    colors: {
      primaryColor: "#ec4899",
      secondaryColor: "#d946ef",
      backgroundColor: "#fdf2f8",
      textColor: "#831843",
      headerBg: "#ffffff",
      footerBg: "#fce7f3",
      cardBg: "#ffffff",
      buttonStyle: "pill",
    },
    fonts: { headingFont: "Inter", bodyFont: "Inter" },
    layout: {
      headerStyle: "default",
      footerStyle: "default",
      cardStyle: "bordered",
      bannerHeight: "medium",
      bannerOverlay: true,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Ürünler", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Alışveriş", links: [{ label: "Tüm Ürünler", href: "/products" }] },
      { title: "Yardım", links: [{ label: "İletişim", href: "/contact" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Pastel Dünya", subtitle: "Yumuşak ve şık tasarımlar", ctaText: "Alışverişe Başla", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
  {
    name: "tech-dark",
    label: "Tech Dark",
    description: "Koyu mavi, teknoloji hissi, modern ve keskin",
    previewColor: "#020617",
    colors: {
      primaryColor: "#38bdf8",
      secondaryColor: "#818cf8",
      backgroundColor: "#020617",
      textColor: "#f8fafc",
      headerBg: "#0f172a",
      footerBg: "#020617",
      cardBg: "#0f172a",
      buttonStyle: "sharp",
    },
    fonts: { headingFont: "Inter", bodyFont: "Monaco" },
    layout: {
      headerStyle: "default",
      footerStyle: "minimal",
      cardStyle: "elevated",
      bannerHeight: "medium",
      bannerOverlay: false,
    },
    headerLinks: [
      { label: "Ana Sayfa", href: "/", order: 1 },
      { label: "Katalog", href: "/products", order: 2 },
    ],
    footerGroups: [
      { title: "Menü", links: [{ label: "Ana Sayfa", href: "/" }, { label: "Katalog", href: "/products" }] },
    ],
    socialLinks: [],
    banner: { imageUrl: "", title: "Teknoloji Koleksiyonu", subtitle: "İleri teknoloji ürünleri", ctaText: "Kataloğu İncele", ctaLink: "/products" },
    seo: { title: "", description: "" },
  },
];

export function getThemeByName(name: string): StoreTheme | undefined {
  return STORE_THEMES.find((t) => t.name === name);
}

export function getDefaultThemeJson(): string {
  return JSON.stringify(STORE_THEMES[0]);
}
