function h2(t: string) { return `<h2>${t}</h2>`; }
function h3(t: string) { return `<h3>${t}</h3>`; }
function p(t: string) { return `<p>${t}</p>`; }
function ul(items: string[]) { return `<ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul>`; }
function ol(items: string[]) { return `<ol>${items.map((i) => `<li>${i}</li>`).join("")}</ol>`; }

const COMPANY = `
<p><strong>İşletme Ünvanı:</strong> Candan Kaynar Ena Unity<br>
<strong>Vergi Dairesi:</strong> Konak Vergi Dairesi<br>
<strong>Vergi Numarası:</strong> 19649091188<br>
<strong>Adres:</strong> Akdeniz Mahallesi Şehit Fethi Bey Caddesi Kızılkanat İş Merkezi No:45 Kat:8 Daire:83 Konak / İzmir<br>
<strong>Telefon:</strong> 0541 188 14 35<br>
<strong>E-Posta:</strong> <a href="mailto:info@enaunity.com.tr">info@enaunity.com.tr</a>, <a href="mailto:enaunity@gmail.com">enaunity@gmail.com</a><br>
<strong>İnternet Sitesi:</strong> <a href="https://www.enaunity.com.tr">www.enaunity.com.tr</a></p>`;

export const KVKK_CONTENT = [
  h2("KİŞİSEL VERİLERİN KORUNMASI VE İŞLENMESİ HAKKINDA AYDINLATMA METNİ"),
  h3("1. VERİ SORUMLUSU"),
  p('6698 Sayılı Kişisel Verilerin Korunması Kanunu ("KVKK") kapsamında kişisel verileriniz, veri sorumlusu sıfatıyla aşağıda bilgileri bulunan işletme tarafından işlenmektedir.'),
  COMPANY,
  p('Bundan sonra "ENA UNITY" olarak anılacaktır.'),
  h3("2. TOPLANAN KİŞİSEL VERİLER"),
  p("ENA UNITY tarafından aşağıdaki kişisel veriler işlenebilmektedir:"),
  h3("Kimlik Bilgileri"),
  ul(["Ad Soyad", "T.C. Kimlik Numarası", "Vergi Kimlik Numarası", "Firma Bilgileri"]),
  h3("İletişim Bilgileri"),
  ul(["Telefon Numarası", "E-Posta Adresi", "Adres Bilgileri", "Teslimat Adresleri", "Fatura Adresleri"]),
  h3("İşlem Güvenliği Verileri"),
  ul(["IP Adresi", "Oturum Bilgileri", "Log Kayıtları", "Çerez Verileri", "Tarayıcı Verileri"]),
  h3("Finansal Veriler"),
  ul(["Ödeme Bilgileri", "Banka Bilgileri", "IBAN Bilgileri", "Muhasebe Kayıtları"]),
  h3("Ticari Veriler"),
  ul(["Sipariş Bilgileri", "Bayilik Bilgileri", "XML Kullanım Bilgileri", "Sistem Kullanım Verileri", "Destek Talepleri", "Tedarikçi Bilgileri"]),
  h3("3. KİŞİSEL VERİLERİN TOPLANMA YÖNTEMİ"),
  p("Kişisel verileriniz; internet sitesi üyelik formları, bayilik başvuru formları, XML başvuru formları, tedarikçi başvuru formları, telefon görüşmeleri, e-posta yazışmaları, canlı destek görüşmeleri, sözleşmeler, ödeme sistemleri, çerezler, sunucu kayıtları, mobil cihazlar ve entegrasyon sistemleri aracılığıyla elektronik veya fiziki ortamda toplanabilmektedir."),
  h3("4. KİŞİSEL VERİLERİN İŞLENME AMAÇLARI"),
  ul([
    "Üyelik oluşturulması",
    "Bayilik başvurularının değerlendirilmesi",
    "XML hizmetlerinin sunulması",
    "Ürün tedarik süreçlerinin yürütülmesi",
    "Sipariş yönetimi",
    "Muhasebe ve faturalandırma işlemleri",
    "Ödeme işlemleri",
    "Müşteri destek hizmetlerinin sunulması",
    "Sistem güvenliğinin sağlanması",
    "Dolandırıcılık ve kötüye kullanımın önlenmesi",
    "Ticari faaliyetlerin yürütülmesi",
    "Sözleşmesel ve yasal yükümlülüklerin yerine getirilmesi",
    "İş sürekliliğinin sağlanması",
    "Performans ve hizmet kalitesinin artırılması",
    "Bilgi güvenliği süreçlerinin yürütülmesi",
  ]),
  h3("5. KİŞİSEL VERİLERİN AKTARILMASI"),
  p("Kişisel verileriniz; yetkili kamu kurum ve kuruluşlarına, mahkemelere, savcılıklara, vergi dairelerine, mali müşavirlere, muhasebe sistemlerine, ödeme kuruluşlarına, bankalara, kargo ve lojistik firmalarına, barındırma ve sunucu hizmeti sağlayıcılarına, yazılım ve entegrasyon hizmet sağlayıcılarına yalnızca ilgili mevzuatın izin verdiği ölçüde aktarılabilmektedir."),
  h3("6. KİŞİSEL VERİLERİN SAKLAMA SÜRESİ"),
  p("Kişisel veriler ilgili mevzuatın öngördüğü süre boyunca veya işleme amacının gerektirdiği süre kadar saklanır. Sürenin sona ermesi halinde kişisel veriler silinir, yok edilir veya anonim hale getirilir."),
  h3("7. KVKK KAPSAMINDAKİ HAKLARINIZ"),
  ul([
    "Kişisel verilerinizin işlenip işlenmediğini öğrenme",
    "İşlenmişse bilgi talep etme",
    "İşlenme amacını öğrenme",
    "Aktarıldığı üçüncü kişileri öğrenme",
    "Eksik veya yanlış işlenen verilerin düzeltilmesini isteme",
    "Silinmesini veya yok edilmesini isteme",
    "Kanuna aykırı işleme nedeniyle zarara uğramanız halinde zararınızın giderilmesini talep etme",
  ]),
  h3("8. BAŞVURU YÖNTEMİ"),
  p('KVKK kapsamındaki taleplerinizi <a href="mailto:info@enaunity.com.tr">info@enaunity.com.tr</a> adresine güvenli elektronik posta ile veya yazılı olarak işletme adresine göndererek iletebilirsiniz. Başvurular mevzuatta öngörülen süreler içerisinde sonuçlandırılacaktır.'),
  p("İşbu Aydınlatma Metni ENA UNITY tarafından güncellenebilir ve güncel sürüm internet sitesi üzerinden yayımlanır."),
].join("\n");

export const COOKIE_CONTENT = [
  h2("ÇEREZ (COOKIE) POLİTİKASI"),
  h3("1. AMAÇ"),
  p("Bu Çerez Politikası, www.enaunity.com.tr internet sitesini ziyaret eden kullanıcıların deneyimini geliştirmek amacıyla kullanılan çerezler hakkında bilgi vermek amacıyla hazırlanmıştır."),
  h3("2. ÇEREZ NEDİR?"),
  p("Çerezler, internet siteleri tarafından cihazınıza kaydedilen küçük veri dosyalarıdır. Bu dosyalar sayesinde kullanıcı tercihleri hatırlanabilir ve internet sitesi daha verimli çalışabilir."),
  h3("3. KULLANILAN ÇEREZ TÜRLERİ"),
  h3("Zorunlu Çerezler"),
  p("Sitenin çalışması için gerekli olan çerezlerdir. Oturum yönetimi, güvenlik doğrulamaları, form işlemleri ve üyelik kontrolleri için kullanılmaktadır."),
  h3("Performans Çerezleri"),
  p("İnternet sitesinin performansını ölçmek amacıyla kullanılır. Hangi sayfaların ziyaret edildiği, hangi içeriklerin görüntülendiği ve hata kayıtları anonim olarak analiz edilebilir."),
  h3("İşlevsellik Çerezleri"),
  p("Kullanıcının tercihlerini hatırlamak amacıyla kullanılabilir. Dil tercihleri, oturum tercihleri ve arayüz ayarları gibi bilgiler saklanabilir."),
  h3("Analitik ve İstatistik Çerezleri"),
  p("İnternet sitesinin geliştirilmesi amacıyla ziyaretçi davranışları analiz edilebilir."),
  h3("Reklam ve Pazarlama Çerezleri"),
  p("Kullanıcılara ilgi alanlarına uygun içerik ve reklam sunulabilmesi amacıyla kullanılabilir."),
  h3("4. TOPLANAN VERİLER"),
  ul(["IP Adresi", "Tarayıcı Bilgileri", "Cihaz Bilgileri", "İşletim Sistemi Bilgileri", "Oturum Süresi", "Sayfa Görüntüleme Bilgileri", "Tıklama Verileri", "Site Kullanım İstatistikleri"]),
  h3("5. ÜÇÜNCÜ TARAF ÇEREZLER"),
  p("Google hizmetleri, analitik araçlar, ödeme sistemleri, entegrasyon servisleri ve barındırma hizmetleri gibi üçüncü taraf hizmet sağlayıcılarına ait çerezler kullanılabilir."),
  h3("6. ÇEREZLERİN YÖNETİMİ"),
  p("Kullanıcılar tarayıcı ayarları üzerinden çerezleri silebilir, engelleyebilir veya belirli çerez türlerine izin verebilir. Çerezlerin devre dışı bırakılması durumunda internet sitesinin bazı bölümleri tam olarak çalışmayabilir."),
  h3("7. GÜNCELLEME"),
  p("ENA UNITY işbu Çerez Politikasını gerekli gördüğü durumlarda güncelleme hakkını saklı tutar. Güncel sürüm internet sitesi üzerinden yayımlandığı tarihte yürürlüğe girer."),
].join("\n");

export const PRIVACY_CONTENT = [
  h2("GİZLİLİK POLİTİKASI"),
  h3("1. AMAÇ"),
  p("İşbu Gizlilik Politikası, www.enaunity.com.tr internet sitesini ziyaret eden kullanıcıların kişisel verilerinin korunması, işlenmesi, saklanması ve güvenliğinin sağlanmasına ilişkin esasları düzenlemek amacıyla hazırlanmıştır."),
  p("Candan Kaynar Ena Unity, kullanıcı gizliliğinin korunmasına önem vermekte olup, yürürlükte bulunan mevzuat kapsamında gerekli teknik ve idari tedbirleri almaktadır."),
  h3("2. TOPLANAN BİLGİLER"),
  ul(["Ad Soyad", "Telefon Numarası", "E-Posta Adresi", "Adres Bilgileri", "Firma Bilgileri", "Vergi Bilgileri", "IP Adresi", "Oturum Bilgileri", "Çerez Verileri", "Sipariş Bilgileri", "Bayilik Bilgileri", "XML Kullanım Bilgileri", "Destek Talepleri"]),
  h3("3. BİLGİLERİN KULLANIM AMACI"),
  ul(["Üyelik işlemlerinin yürütülmesi", "Bayilik başvurularının değerlendirilmesi", "XML hizmetlerinin sunulması", "Sipariş süreçlerinin yönetilmesi", "Teknik destek verilmesi", "Sistem güvenliğinin sağlanması", "Muhasebe ve yasal yükümlülüklerin yerine getirilmesi", "Hizmet kalitesinin geliştirilmesi"]),
  h3("4. BİLGİLERİN KORUNMASI"),
  p("ENA UNITY; yetkisiz erişim, veri kaybı, veri sızıntısı, veri değişikliği ve kötü niyetli kullanım risklerine karşı gerekli teknik ve idari önlemleri uygulamayı hedeflemektedir."),
  h3("5. ÜÇÜNCÜ KİŞİLERE AKTARIM"),
  p("Kullanıcı bilgileri; yasal zorunluluklar, mahkeme kararları, yetkili kamu kurumları, vergisel yükümlülükler, ödeme kuruluşları ve kargo firmaları haricinde üçüncü kişilere satılmaz veya ticari amaçla devredilmez."),
  h3("6. SAKLAMA SÜRESİ"),
  p("Kişisel veriler ilgili mevzuatın öngördüğü süreler boyunca veya işleme amacının gerektirdiği süre kadar saklanır. Sürenin sona ermesi halinde silinir, yok edilir veya anonim hale getirilir."),
  h3("7. KULLANICI HAKLARI"),
  p('Kullanıcılar KVKK kapsamında sahip oldukları hakları kullanmak amacıyla <a href="mailto:info@enaunity.com.tr">info@enaunity.com.tr</a> adresi üzerinden başvuruda bulunabilirler.'),
  h3("8. GÜNCELLEME"),
  p("ENA UNITY işbu politikayı güncelleme hakkını saklı tutar. Güncel sürüm internet sitesinde yayımlandığı tarihte yürürlüğe girer."),
].join("\n");

export const MEMBERSHIP_CONTENT = [
  h2("ÜYELİK VE PLATFORM KULLANIM SÖZLEŞMESİ"),
  h3("Madde 1 – Taraflar"),
  p("İşbu Üyelik ve Platform Kullanım Sözleşmesi, www.enaunity.com.tr internet sitesi ile bu site üzerinden sunulan tüm hizmetleri işleten Candan Kaynar Ena Unity (Vergi No: 19649091188, Konak Vergi Dairesi) bundan sonra \"ENA UNITY\" olarak anılacaktır."),
  COMPANY,
  p("İnternet sitesine üye olan gerçek veya tüzel kişi bundan sonra \"ÜYE\" olarak anılacaktır. Üye, işbu sözleşmeyi elektronik ortamda onaylamakla tüm hükümleri kabul etmiş sayılır."),
  h3("Madde 2 – Sözleşmenin Konusu"),
  p("Bayilik sistemleri, XML veri hizmetleri, ürün tedarik hizmetleri, dropshipping hizmetleri, yazılım hizmetleri, HIVE platformu, THYRONIX platformu, entegrasyon sistemleri, pazaryeri bağlantıları, ürün yönetim sistemleri ve internet sitesi üzerinden sunulan diğer hizmetlerin kullanım şartlarını düzenlemektedir."),
  h3("Madde 3 – Üyelik Şartları"),
  p("Üye; doğru ve güncel bilgiler vermeyi, kendi hesabını korumayı, şifresini üçüncü kişilerle paylaşmamayı, sistem güvenliğini ihlal etmemeyi ve hukuka aykırı işlem yapmamayı kabul eder. Yanlış bilgi verilmesinden kaynaklanan tüm sorumluluk üyeye aittir."),
  h3("Madde 4 – Hesap Güvenliği"),
  p("Üye hesabı yalnızca ilgili üyeye aittir. Hesap bilgileri, şifreler ve erişim kodları üçüncü kişilerle paylaşılamaz. Hesap üzerinden yapılan tüm işlemler kullanıcı tarafından gerçekleştirilmiş kabul edilir."),
  h3("Madde 5 – Sunulan Hizmetler"),
  p("ENA UNITY bayilik, XML, tedarik, dropshipping, pazaryeri entegrasyonları, yazılım lisansları, abonelik sistemleri, danışmanlık, dijital hizmetler, API ve veri aktarım hizmetlerinden bir veya birkaçını sağlayabilir."),
  h3("Madde 6 – Fikri ve Sınai Haklar"),
  p("Site üzerindeki tasarım, yazılım, kod, marka, logo, veritabanı, katalog ve içerikler ENA UNITY'nin veya hak sahiplerinin mülkiyetindedir. Kopyalama, çoğaltma, satma, yayma, kiralama ve tersine mühendislik yasaktır."),
  h3("Madde 7 – Yasaklı Kullanımlar"),
  p("Sisteme zarar verme, yetkisiz veri toplama, bot kullanımı, sahte üyelik, spam ve üçüncü kişilerin haklarını ihlal kesin olarak yasaktır."),
  h3("Madde 8 – Hizmet Sürekliliği"),
  p("Bakım, güncelleme, sunucu değişiklikleri ve güvenlik çalışmaları nedeniyle hizmetler geçici olarak durdurulabilir."),
  h3("Madde 9 – Sorumluluğun Sınırlandırılması"),
  p("ENA UNITY; internet kesintileri, sunucu arızaları, üçüncü taraf hizmet sorunları, ödeme kuruluşları, kargo gecikmeleri ve mücbir sebepler nedeniyle oluşabilecek dolaylı zararlardan sorumlu değildir."),
  h3("Madde 10 – Üyeliğin Askıya Alınması ve Sonlandırılması"),
  p("Sözleşme ihlali, sahte bilgi, kötüye kullanım, hukuka aykırı faaliyetler ve ödeme yükümlülüklerinin yerine getirilmemesi halinde üyelik sonlandırılabilir."),
  h3("Madde 11 – Delil Sözleşmesi"),
  p("Sistem kayıtları, sunucu logları, veritabanı kayıtları, e-posta ve ödeme kayıtları HMK 193 kapsamında kesin delil niteliğindedir."),
  h3("Madde 12 – Uygulanacak Hukuk ve Yetki"),
  p("Türk Hukuku uygulanacaktır. İzmir Mahkemeleri ve İzmir İcra Daireleri yetkilidir."),
  h3("Madde 13 – Yürürlük"),
  p("Sözleşme üyelik oluşturulduğu anda yürürlüğe girer."),
].join("\n");

export const DEALER_CONTENT = [
  h2("BAYİLİK, XML VERİ HİZMETLERİ VE DROPSHIPPING HİZMET SÖZLEŞMESİ"),
  h3("Madde 1 – Taraflar"),
  p("Candan Kaynar Ena Unity (Vergi No: 19649091188) \"ENA UNITY\"; diğer tarafta bayi/satıcı/XML kullanıcısı olarak kayıt olan kişi \"BAYİ\"."),
  h3("Madde 2 – Sözleşmenin Konusu"),
  p("Bayilik, XML veri erişimi, dropshipping, ürün tedarik ve sipariş yönetim süreçlerinin usul ve esaslarını düzenler."),
  h3("Madde 3 – Bayilik Sistemi"),
  p("Bayilik sistemi ticari amaçlıdır. Ürün katalogları, XML erişimi, entegrasyon, özel fiyatlar ve kampanyalar sunulabilir."),
  h3("Madde 4 – Bayilik Ücreti"),
  p("Bayilik sistemine katılım bedeli 10.000 TL + KDV olarak belirlenmiştir. Tek seferlik tahsil edilir."),
  h3("Madde 5 – Bayilik Ücretinin İadesi"),
  p("Bayilik aktivasyonu tamamlandıktan sonra üyelik, kurulum, aktivasyon ve tanımlama bedelleri iade edilmez."),
  h3("Madde 6 – XML Veri Hizmeti"),
  p("XML verileri ürün bilgileri, stok, görseller, kategori ve fiyat verilerini içerebilir. Yalnızca bayinin kendi ticari faaliyetleri kapsamında kullanılabilir."),
  h3("Madde 7 – XML Verilerinin Korunması"),
  p("XML verileri ve kataloglar üçüncü kişilere satılamaz, devredilemez, kiralanamaz veya yeniden dağıtılamaz."),
  h3("Madde 8 – Hesap Devri Yasağı"),
  p("Bayilik hesaplarının satılması, kiralanması veya devredilmesi yasaktır."),
  h3("Madde 9 – Fiyat ve Stok Bilgileri"),
  p("Stok ve fiyat verileri anlık değişebilir. ENA UNITY ticari kayıplardan sorumlu tutulamaz."),
  h3("Madde 10 – Dropshipping Hizmetleri"),
  p("Sevkiyat ENA UNITY, tedarikçi veya lojistik firmaları tarafından gerçekleştirilebilir."),
  h3("Madde 11 – Ürün Görselleri ve İçerikleri"),
  p("Ürün içerikleri bilgilendirme amaçlıdır. Tedarikçi kaynaklı değişikliklerden ENA UNITY sorumlu değildir."),
  h3("Madde 12 – Hasarlı veya Yanlış Ürünler"),
  p("Teslim tarihinden itibaren en geç 3 iş günü içinde bildirim yapılmalıdır. Kargo tanzim tutanağı ve fotoğraflar zorunludur."),
  h3("Madde 13 – Dijital Hizmetler"),
  p("XML, entegrasyon, API, kurulum ve danışmanlık hizmetleri aktif edildikten sonra iade edilemez."),
  h3("Madde 14 – Hizmetlerin Askıya Alınması"),
  p("Ödeme gecikmesi, sözleşme ihlali, XML paylaşımı ve yasadışı kullanım halinde hizmetler askıya alınabilir."),
  h3("Madde 15 – Tazminat"),
  p("Hukuka aykırı faaliyetlerden doğan zararlar bayiden talep edilebilir."),
  h3("Madde 16 – Yetki"),
  p("İzmir Mahkemeleri ve İzmir İcra Daireleri yetkilidir."),
].join("\n");

export const HIVE_THYRONIX_CONTENT = [
  h2("HIVE VE THYRONIX YAZILIM HİZMETLERİ KULLANIM VE ABONELİK SÖZLEŞMESİ"),
  h3("Madde 1 – Tanımlar"),
  p("HIVE: SEO, GEO, içerik, analiz ve otomasyon platformu. THYRONIX: otomasyon, entegrasyon, yapay zeka ve dijital operasyon platformu. KULLANICI: ilgili yazılımları kullanan gerçek veya tüzel kişi."),
  h3("Madde 2 – Hizmetin Niteliği"),
  p("Bulut tabanlı yazılım hizmetleridir. Mülkiyet devredilmez; sınırlı, geri alınabilir kullanım hakkı tanınır."),
  h3("Madde 3 – Lisans Kapsamı"),
  p("Yazılım yalnızca kullanıcının kendi ticari faaliyetleri kapsamında kullanılabilir. Kopyalama, satma, kiralanma ve tersine mühendislik yasaktır."),
  h3("Madde 4 – Abonelik Süresi"),
  p("Aylık veya yıllık sunulabilir. Süre bitiminde erişim kısıtlanabilir."),
  h3("Madde 5 – Ücretlendirme"),
  p("Abonelik ücretleri sitede belirtilen tutarlardan tahsil edilir. Fiyat değişiklikleri yeni dönemlerde uygulanır."),
  h3("Madde 6 – Ödeme Yükümlülüğü"),
  p("Ücretler peşin tahsil edilir. Gecikmede erişim kısıtlanabilir veya durdurulabilir."),
  h3("Madde 7 – İade Politikası"),
  p("Erişim sağlandıktan sonra abonelik, kurulum, aktivasyon ve lisans ücretleri iade edilmez."),
  h3("Madde 8 – Hizmet Garantisi Bulunmaması"),
  p("Belirli sıralama, trafik, satış veya gelir garanti edilmez."),
  h3("Madde 9 – Yapay Zeka Çıktıları"),
  p("Kullanıcı üretilen içerikleri yayınlamadan önce kontrol etmekle yükümlüdür."),
  h3("Madde 10 – Üçüncü Taraf Platformlar"),
  p("Google, OpenAI, Meta ve diğer platformların politika değişikliklerinden ENA UNITY sorumlu değildir."),
  h3("Madde 11 – Hizmet Kesintileri"),
  p("Bakım, güncelleme, siber saldırı ve altyapı sorunları nedeniyle geçici kesintiler yaşanabilir."),
  h3("Madde 12 – Kullanıcı Verileri"),
  p("Yüklenen içeriklerin hukuka uygunluğundan kullanıcı sorumludur."),
  h3("Madde 13 – Yasaklı Kullanımlar"),
  p("Spam, yasadışı içerik, fikri mülkiyet ihlali ve sisteme zarar verme yasaktır."),
  h3("Madde 14 – Hesabın Sonlandırılması"),
  p("Sözleşme ihlali ve ödeme gecikmesinde erişim sonlandırılabilir."),
  h3("Madde 15 – Sorumluluğun Sınırlandırılması"),
  p("Dolaylı zararlardan sorumluluk kabul edilmez. Toplam sorumluluk son abonelik dönemi tutarı ile sınırlıdır."),
  h3("Madde 16 – Mücbir Sebepler"),
  p("Doğal afet, salgın, savaş, siber saldırı ve altyapı sorunları mücbir sebep sayılır."),
  h3("Madde 17 – Yetki"),
  p("İzmir Mahkemeleri ve İzmir İcra Daireleri yetkilidir."),
].join("\n");

export const REFUND_CONTENT = [
  h2("İADE, DEĞİŞİM, HASARLI ÜRÜN VE TESLİMAT POLİTİKASI"),
  h3("1. AMAÇ"),
  p("Candan Kaynar Ena Unity tarafından sunulan bayilik, tedarik, XML, dropshipping ve yazılım hizmetlerine ilişkin süreçleri düzenler."),
  h3("2. HİZMET MODELİ"),
  p("ENA UNITY B2B hizmet modeli ile faaliyet göstermektedir."),
  h3("3. BAYİLİK ÜCRETLERİ"),
  p("Bayilik hesabı oluşturulduktan ve erişim tanımlandıktan sonra bayilik bedeli iade edilmez."),
  h3("4. XML HİZMETLERİ"),
  p("XML erişimi tanımlandıktan sonra XML hizmet bedelleri iade edilmez."),
  h3("5. YAZILIM HİZMETLERİ"),
  p("HIVE, THYRONIX ve benzeri yazılım hizmetlerinde erişim sağlandıktan sonra ücretler iade edilmez."),
  h3("6. ÜRÜN TESLİMATLARI"),
  p("Teslimat süreleri ürün, stok, üretim ve lojistik koşullarına göre değişebilir."),
  h3("7. KARGO TESLİMATI SIRASINDA KONTROL"),
  p("Ambalajı hasarlı gönderilerde kargo görevlisine tutanak tutturulmalıdır."),
  h3("8. HASARLI ÜRÜN BİLDİRİMİ"),
  p("Teslim tarihinden itibaren en geç 3 iş günü içinde bildirim yapılmalıdır."),
  h3("9. ZORUNLU BELGELER"),
  ul(["Kargo tanzim tutanağı", "Ürün fotoğrafları", "Paket fotoğrafları", "Kargo etiketi", "Sipariş bilgileri"]),
  h3("10. ÇÖZÜM YÖNTEMİ"),
  p("Haklı bulunan taleplerde eksik/yanlış ürün tamamlanabilir veya yeniden gönderim yapılabilir."),
  h3("11. STOK TÜKENMESİ"),
  p("Stok farklılıkları ticari hayatın doğal sonucu olarak değerlendirilir."),
  h3("12. FİYAT DEĞİŞİKLİKLERİ"),
  p("Fiyatlar döviz, tedarik ve lojistik maliyetlerine göre güncellenebilir."),
  h3("13. TESPİT EDİLEMEYEN HASARLAR"),
  p("Geç bildirilen veya belgesiz talepler kabul edilmeyebilir."),
  h3("14. MÜCBİR SEBEPLER"),
  p("Deprem, sel, salgın, savaş, grev ve siber saldırılar mücbir sebep sayılır."),
  h3("15. POLİTİKANIN GÜNCELLENMESİ"),
  p("Güncel sürüm internet sitesinde yayımlandığı tarihte yürürlüğe girer."),
].join("\n");

export const COMMERCIAL_MESSAGE_CONTENT = [
  h2("TİCARİ ELEKTRONİK İLETİ ONAYI"),
  p("Tarafıma kampanya, duyuru, bilgilendirme, özel teklifler, sistem güncellemeleri, ürün ve hizmet tanıtımları ile teknik bilgilendirmeler gönderilmesini kabul ediyorum."),
  p("ENA UNITY tarafından SMS, telefon, e-posta, WhatsApp ve bildirim sistemleri aracılığıyla tarafımla iletişime geçilebileceğini kabul ederim."),
  p("Dilediğim zaman iletişim izinlerimi geri çekebileceğimi biliyorum."),
].join("\n");

export type LegalContractSeed = {
  title: string;
  slug: string;
  type: string;
  category: string;
  content: string;
};

export const LEGAL_CONTRACT_SEEDS: LegalContractSeed[] = [
  { title: "KVKK Aydınlatma Metni", slug: "kvkk-aydinlatma-metni", type: "public", category: "kvkk", content: KVKK_CONTENT },
  { title: "Çerez Politikası", slug: "cerez-politikasi", type: "public", category: "cookie", content: COOKIE_CONTENT },
  { title: "Gizlilik Politikası", slug: "gizlilik-politikasi", type: "public", category: "privacy", content: PRIVACY_CONTENT },
  { title: "Üyelik ve Platform Kullanım Sözleşmesi", slug: "uyelik-sozlesmesi", type: "public", category: "membership", content: MEMBERSHIP_CONTENT },
  { title: "Ticari Elektronik İleti Onayı", slug: "ticari-elektronik-ileti-onayi", type: "public", category: "commercial", content: COMMERCIAL_MESSAGE_CONTENT },
  { title: "Bayilik, XML ve Dropshipping Hizmet Sözleşmesi", slug: "bayilik-xml-dropshipping-sozlesmesi", type: "dealer", category: "dealer", content: DEALER_CONTENT },
  { title: "HIVE ve THYRONIX Yazılım Hizmetleri Sözleşmesi", slug: "hive-thyronix-sozlesmesi", type: "module", category: "module", content: HIVE_THYRONIX_CONTENT },
  { title: "İade, Değişim, Hasarlı Ürün ve Teslimat Politikası", slug: "iade-degisim-teslimat-politikasi", type: "public", category: "refund", content: REFUND_CONTENT },
  { title: "Mesafeli Satış Sözleşmesi", slug: "mesafeli-satis-sozlesmesi", type: "public", category: "legacy", content: "<h2>Mesafeli Satış Sözleşmesi</h2><p>6502 sayılı Kanun kapsamında düzenlenmiştir. Güncel metin için Üyelik Sözleşmesi ve İade Politikası geçerlidir.</p>" },
  { title: "Bayi / Tedarikçi Sözleşmesi", slug: "bayi-sozlesmesi", type: "dealer", category: "legacy", content: "<h2>Bayi Sözleşmesi</h2><p>Güncel metin için Bayilik, XML ve Dropshipping Hizmet Sözleşmesi geçerlidir.</p>" },
];
