ALTER TABLE "Product" ADD COLUMN "seoTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "seoDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "seoKeywords" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "seoCanonicalUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "geoTargetsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Product" ADD COLUMN "aeoAnswerSummary" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "aeoFaqJson" TEXT NOT NULL DEFAULT '[]';
